Add Linux IN_CLOSE_WRITE support
fsnotify/fsnotify pull request #313
Opened 2019-10-16 11:57 UTC by bevand10

#### What does this pull request do?
Adds support for the Linux inotify IN_CLOSE_WRITE event. This is triggered when a file writer/modifier has finished making changes to a file (e.g. if use is monitoring a FTP upload folder, event is fired when a new file has finished being written).

#### Where should the reviewer start?
fsnotify.go has an extra Op flag: CloseWrite
inotify.go has changes that add the IN_CLOSE_WRITE flag.

#### How should this be manually tested?
Run an app monitoring any directory. Open a file for write (e.g. using vim). On file close (:wq in vim) the IN_CLOSE_WRITE event will be triggered.

2020-02-17 18:01 UTC, simon04 commented
This addition has been discussed/declined already a few times in the past: #252 #235 #202 #191 #173 #22

2021-01-07 21:22 UTC, jbrindle commented
It's been 6 years and you haven't come up with "cross-platform" way to do this, could you allow options for platforms that support them and not for ones that don't, like any OS level cross platform project?

2021-03-09 23:08 UTC, ronakg commented
I'm not sure what's the issue with this particular change. It's not like it conflicts with other options in the package. `CloseWrite` provides a way to monitor another event for the users of `fsnotify`.

2021-08-12 13:05 UTC, chamber2018 commented
LGTM

2021-08-18 01:12 UTC, nathany requested changes
Thanks for the contribution.

`IN_CLOSE_WRITE` has come up many times over the years, but so far nobody has provided a suitable solution. `fsnotify` is a cross-platform library. Adding a `CloseWrite` op that only functions on Linux is a non-starter. Consideration must be given to how things will work on BSD, Windows, macOS, and Solaris.

2021-08-24 00:53 UTC, nathany commented
Please move this to a discussion #392.

2021-08-24 00:53 UTC, closed without merging