Add a feature to return the directories and files that are being monitored
fsnotify/fsnotify pull request #374
Opened 2021-07-28 10:44 UTC by NitroCao

#### What does this pull request do?
Add a method for `Watcher` to return the directories and files that are being monitored.

#### Where should the reviewer start?
`WatchList` method in `inotify.go`.

#### How should this be manually tested?
unit testing in `inotify_test.go`.

2021-07-29 20:22 UTC, PaluMacil approved these changes
Looks appropriate and tested

2021-07-31 01:48 UTC, nathany requested changes
Thanks for the contribution.

Unfortunately we can't add a new `WatchList()` API that only works on Linux.

`fsnotify` is a cross-platform library. If we want to add `WatchList()`, it must also be added for macOS/BSD (kqueue) and Windows.

2022-01-15 13:16 UTC, mattn commented
@NitroCao Would you update this?

2022-01-19 01:08 UTC, nathany commented on inotify.go
> +func (w *Watcher) WatchList() []string {
Be careful with adding new APIs that don't exist on other platforms. We want to keep a uniform API to the underlying systems.

@mattn

2022-04-08 08:04 UTC, chamabreu commented
Hi, is this feature comming?

2022-04-19 13:01 UTC, mattn commented on windows.go
> +	var entries []string
```suggestion
	entries := make([]string, len(w.watches), len(w.watches))
```

2022-04-19 13:15 UTC, NitroCao commented on windows.go
> +	var entries []string
Thanks for reply. updated.

2022-04-19 14:20 UTC, mattn commented
@nathany do you have opinion others?

2022-04-19 18:44 UTC, nathany commented
LGTM

2022-04-20 04:26 UTC, mattn commented
Thanks. I want to confirm rules for mainteners. Only administrators have to merge this? (I know I can merge this)

![image](https://user-images.githubusercontent.com/10111/164150214-16bf515c-2b7f-4ab4-abef-ebdbd49aaf45.png)

2022-04-21 01:36 UTC, nathany commented
Looks like there is a problem with Hound

2022-04-21 01:38 UTC, nathany commented
I removed Hound and the branch protection rule that required it.

2022-04-21 01:38 UTC, nathany approved these changes

2022-04-21 06:18 UTC, NitroCao commented
So can we merge this PR now?

2022-04-21 06:46 UTC, merged

2022-04-21 06:46 UTC, mattn commented
Thank you

2022-04-21 23:44 UTC, nathany commented
thanks @mattn 

I see there is a 1.5.3 tag that was created before the 1.5.2 tag for this. Will that cause problems getting this update?

2022-04-22 01:24 UTC, mattn commented
OpenBSD build was broken since before. https://github.com/fsnotify/fsnotify/pull/443