pass testing.T explicitly to the anonymous func
fsnotify/fsnotify pull request #414
Opened 2022-01-14 13:45 UTC by hidetatz

NOTE: Please do not open a pull request that adds or changes the public API without giving consideration to all supported operating systems.

#### What does this pull request do?

Passes testing.T explicitly to the anonymous function run as a goroutine. By this change, `go vet` succeeds.

#### Where should the reviewer start?

Read https://github.com/fsnotify/fsnotify/issues/412 to understand the problem.

#### How should this be manually tested?

Run `go vet` locally.

2022-01-14 15:26 UTC, shogo82148 requested changes
Thanks for your contribution, but it just deceives `go vet` and is not an essential solution.
We need to wait for all the goroutines to finish before calling `(*T).Fatalf`.

2022-01-14 23:53 UTC, nathany commented
I did see some example solutions when I searched the Internet for the vet error... there's a better way to do it, I'm certain.

Little point in running go vet if we're going to trick it.

2022-01-14 23:53 UTC, closed without merging

2022-01-14 23:58 UTC, hidetatz commented
Does it make sense to use errgroup? I'm writing patch like this:

```diff
diff --git a/inotify_poller_test.go b/inotify_poller_test.go
index 0570057..80a2bb5 100644
--- a/inotify_poller_test.go
+++ b/inotify_poller_test.go
@@ -11,6 +11,7 @@ import (
 	"testing"
 	"time"
 
+	"golang.org/x/sync/errgroup"
 	"golang.org/x/sys/unix"
 )
 
@@ -174,19 +175,23 @@ func TestPollerConcurrent(t *testing.T) {
 	oks := make(chan bool)
 	live := make(chan bool)
 	defer close(live)
-	go func(tb testing.TB) {
+	eg := errgroup.Group{}
+	eg.Go(func() error {
 		defer close(oks)
 		for {
 			ok, err := poller.wait()
 			if err != nil {
-				tb.Fatalf("poller failed: %v", err)
+				return err
 			}
 			oks <- ok
 			if !<-live {
-				return
+				return nil
 			}
 		}
-	}(t)
+	})
+	if err := eg.Wait(); err != nil {
+		t.Fatalf("poller failed: %v", err)
+	}
 
 	// Try a write
 	select {

```

2022-01-15 00:04 UTC, nathany commented
That looks like a very nice solution

It does mean adding another dependency, but only for tests. 🤔

2022-01-15 00:14 UTC, hidetatz commented
Another way is using sync.WaitGroup instead of errgroup if introducing another dependency is unacceptable, but using errgroup is clearer way for me.
OK, I'll open another PR. 

> There are multiple platforms where the vet error occurs.

Got it, I think something like `GOOS=windows GOARCH=amd64 go vet ./...` will work.

2022-01-15 00:21 UTC, nathany commented
👍🏼 I'll let you decide -- if you can make sync.WaitGroup work nicely (maybe adding a helper function or what not), that may be preferred.

Kind've need a way to trigger the error case to make sure it all works, because normally Fatalf shouldn't be called. :-)